services:
  php:
    build:
      context: ./docker/php8.1
      args:
        uid: "${UID-1000}"
        gid: "${GID-1000}"
    container_name: "laravel_php"
    image: app/php8.3
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - "${APP_PHP_PORT}:9000"
  nginx:
    build:
      context: ./docker/nginx
    container_name: laravel_nginx
    image: app/nginx
    restart: always
    tty: true
    ports:
      - "127.0.0.1:${APP_NGINX_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
  mysql:
    image: mysql:8.3
    container_name: laravel_mysql
    restart: always
    tty: true
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    ports:
      - "${APP_MYSQL_PORT}:3306"
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  mysqldata:
    driver: local
